# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Assert variables are defined
  ansible.builtin.assert:
    that:
    - region is defined
    - custom_vars.project is defined

- name: Get cluster credentials for kubectl
  delegate_to: localhost
  ansible.builtin.command: gcloud container clusters get-credentials {{ deployment_name }} --region {{ cli_deployment_vars.region }} --project {{ custom_vars.project }} --verbosity=debug

- name: Run the FIO benchmark job and get its name
  delegate_to: localhost
  ansible.builtin.shell: |
    job_file=({{ workspace }}/{{ deployment_name }}/primary/fio-benchmark*)
    # Assuming only one benchmark file matches
    kubectl create -f "${job_file[0]}" -o=jsonpath='{.metadata.name}'
  args:
    executable: /bin/bash
  register: fio_job_create_output

- name: Set FIO job name
  ansible.builtin.set_fact:
    fio_job_name: "{{ fio_job_create_output.stdout }}"

- name: Wait for FIO Job to complete
  # The FIO job should take approximately 20 minutes, process times out after a max wait of 40 mins
  delegate_to: localhost
  ansible.builtin.shell: "kubectl get job {{ fio_job_name }} -o jsonpath='{.status.succeeded}'"
  register: fio_job_status
  until: fio_job_status.stdout == '1'
  retries: 80
  delay: 30

- name: Fetch logs from the FIO job pod and save to fio_pod_logs.txt
  delegate_to: localhost
  ansible.builtin.shell: |
    pod_name="$(kubectl get pods -l job-name={{ fio_job_name }} -o jsonpath='{.items[0].metadata.name}')"
    kubectl logs "$pod_name" > fio_pod_logs.txt
    cat fio_pod_logs.txt
  register: fio_test_logs

- name: Print the FIO test logs
  debug:
    msg: "{{fio_test_logs.stdout}}"

- name: Clean up FIO job
  delegate_to: localhost
  ansible.builtin.shell: |
    kubectl delete job {{ fio_job_name }} -v=9
